comment:
  header: Hi, there.
  footer: "\
    ---\n\n\
    > This is an automated comment created by the [{{ owner }}/{{ repo }}]. \
    Responding to the bot or mentioning it won't have any effect.\n\n\
    [{{ owner }}/{{ repo }}]: https://github.com/{{ owner }}/{{ repo }}"

labels:
  - name: invalid
    labeled:
      issue:
        body: Please follow the {{ eventName }} templates.
        action: close
      pr:
        body: Thank you @{{ author }} for suggesting this. Please follow the {{ eventName }} templates.
        action: close
        draft: true
    unlabeled:
      issue:
        body: Thank you for following the template. The repository owner will reply.
        action: open
  - name: forum
    labeled:
      issue:
        body: |
          Please ask questions about GitHub Actions at the following forum.
          https://github.community/c/github-actions
        action: close
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This {{ eventName }} already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This {{ eventName }} is easy for contributing. Everyone can work on this.
  - name: proposal
    labeled:
      issue:
        body: &proposal_body Thank you @{{ author }} for suggesting this.
      discussion:
        body: *proposal_body
  - name: locked (spam)
    labeled:
      issue:
        body: &locked_spam_body |
          This {{ eventName }} \#{{ number }} has been **LOCKED** with the label {{ labelName }}!

          Please do not spam messages on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: *locked_spam_body
        action: close
        locking: lock
        lock_reason: spam
      discussion:
        body: *locked_spam_body
        locking: lock
        lock_reason: spam
        answer: true
  - name: locked (heated)
    labeled:
      issue:
        body: &locked_heated_labeled_body |
          This {{ eventName }} has been **LOCKED** because of heated conversation!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
      pr:
        body: *locked_heated_labeled_body
        locking: lock
        lock_reason: too heated
        draft: true
      discussion:
        body: *locked_heated_labeled_body
        locking: lock
        lock_reason: too heated
    unlabeled:
      issue:
        body: &locked_heated_unlabeled_body This {{ eventName }} has been unlocked now.
        locking: unlock
      pr:
        body: *locked_heated_unlabeled_body
        locking: unlock
        draft: false
      discussion:
        body: *locked_heated_unlabeled_body
        locking: unlock
  - name: locked (off-topic)
    labeled:
      issue:
        body: |
          This {{ eventName }} has been **LOCKED** because of off-topic conversations!

          Please use our other means of communication for casual chats.
        action: close
        locking: lock
        lock_reason: off-topic
  - name: locked (resolved)
    labeled:
      issue:
        body: |
          This {{ eventName }} has been **LOCKED** because of it being resolved!

          The {{ eventName }} has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new {{ eventName }} instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
