name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*/*/v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # https://github.com/actions/checkout/releases/tag/v3.6.0
        with:
          fetch-depth: 0
          ref: ${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.ref_name }}
          persist-credentials: false
      - name: Dump github context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
      - name: Dump
        run: |
          echo "github.head_ref: ${{ github.head_ref || 'main' }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "actions/checkout.with.ref: ${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.ref_name }}"
      - name: Set envs
        run: |
          if [[ "${{ github.head_ref || 'main' }}" = "main" ]]; then
            echo "GCP_PROJECT_ID=gcp-dev" | tee -a "${GITHUB_ENV}"
            echo "TAG=latest" | tee -a "${GITHUB_ENV}"
          else
            echo "GCP_PROJECT_ID=gcp-prd" | tee -a "${GITHUB_ENV}"
            echo "TAG=${{ github.ref_name }}" | tee -a "${GITHUB_ENV}"
          fi
      - name: Dump envs
        run: echo "${GCP_PROJECT_ID} ${TAG}"
