name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.sha }}
      - name: Dump github context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
      - run: echo ${{ github.sha }}
