name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: main
        if: github.ref_name == 'main'
        run: echo "${{ github.ref_name }} "
      - name: pull-request
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event_name }} "
