name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo "${{ github.event_name == 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name != 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name == 'pull_request' && 'docker' }}"
          echo "${{ github.event_name == 'pull_request' || 'registry' }}"
          echo "${HOME}"
          ls -la "${HOME}"
      - name: Dump step1
        id: step1
        env:
          GH_CTX: ${{ toJson(github) }}
          GH_ENV: ${{ toJson(env) }}
          GH_VARS: ${{ toJson(vars) }}
          GH_JOB: ${{ toJson(job) }}
          GH_STEPS: ${{ toJson(steps) }}
          GH_RUNNER: ${{ toJson(runner) }}
          GH_INPUTS: ${{ toJson(inputs) }}
        run: |
          env | sort
          echo "${GH_CTX}"
          echo "${GH_ENV}"
          echo "${GH_VARS}"
          echo "${GH_JOB}"
          echo "${GH_STEPS}"
          echo "${GH_RUNNER}"
          echo "${GH_INPUTS}"
          jq < "${GITHUB_EVENT_PATH}"
      - name: Dump step2
        id: step2
        env:
          GH_CTX: ${{ toJson(github) }}
          GH_ENV: ${{ toJson(env) }}
          GH_VARS: ${{ toJson(vars) }}
          GH_JOB: ${{ toJson(job) }}
          GH_STEPS: ${{ toJson(steps) }}
          GH_RUNNER: ${{ toJson(runner) }}
          GH_INPUTS: ${{ toJson(inputs) }}
        run: |
          env | sort
          echo "${GH_CTX}"
          echo "${GH_CTX}"
          echo "${GH_ENV}"
          echo "${GH_VARS}"
          echo "${GH_JOB}"
          echo "${GH_STEPS}"
          echo "${GH_RUNNER}"
          echo "${GH_INPUTS}"
          jq < "${GITHUB_EVENT_PATH}"
      - name: Dump without step id
        env:
          GH_CTX: ${{ toJson(github) }}
          GH_ENV: ${{ toJson(env) }}
          GH_VARS: ${{ toJson(vars) }}
          GH_JOB: ${{ toJson(job) }}
          GH_STEPS: ${{ toJson(steps) }}
          GH_RUNNER: ${{ toJson(runner) }}
          GH_INPUTS: ${{ toJson(inputs) }}
        run: |
          env | sort
          echo "${GH_CTX}"
          echo "${GH_CTX}"
          echo "${GH_ENV}"
          echo "${GH_VARS}"
          echo "${GH_JOB}"
          echo "${GH_STEPS}"
          echo "${GH_RUNNER}"
          echo "${GH_INPUTS}"
          jq < "${GITHUB_EVENT_PATH}"
