name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: test
        run: |
          echo "${{ github.event_name == 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name != 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name == 'pull_request' && 'docker' }}"
          echo "${{ github.event_name == 'pull_request' || 'registry' }}"
          echo "${HOME}"
          ls -la "${HOME}"
      - name: uname
        run: |
          echo "uname -a: $(uname -a)"
          echo "uname -s: $(uname -s)"
          echo "uname -n: $(uname -n)"
          echo "uname -r: $(uname -r)"
          echo "uname -v: $(uname -v)"
          echo "uname -m: $(uname -m)"
          echo "uname -p: $(uname -p)"
          echo "uname -o: $(uname -o)"

  dump:
    name: dump ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Dump step1
        # if: false
        id: step1
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
          # env | sort
          # jq < "${GITHUB_EVENT_PATH}"
      - name: Dump step2
        if: false
        id: step2
        run: |
          jq < "${GITHUB_EVENT_PATH}"
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
      - name: Dump without step id
        if: false
        run: |
          jq < "${GITHUB_EVENT_PATH}"
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
