name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # https://github.com/actions/checkout/releases/tag/v3.6.0
      - name: Dump GitHub context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
      - run: echo ${{ github.head_ref || "main" }}
