name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*/*/v*"
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 1
    steps:
      - name: Setup
        run: |
          mkdir -p ~/.iris
          cat "iris" > ~/.iris/config.json
      - uses: actions/upload-artifact@v3
        with:
          name: iris-config-json
          path: ~/.iris

  build:
    needs: [prepare]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: iris-config-json
      - name: Debug
        run: |
          ls -la ~/.iris
          cat ~/.iris/config.json
