name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: github.event.repository.default_branch
        run: echo "${{ github.event.repository.default_branch }}"
      - name: test
        run: |
          echo "${{ github.event_name == 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name != 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name == 'pull_request' && 'docker' }}"
          echo "${{ github.event_name == 'pull_request' || 'registry' }}"
          echo "${HOME}"
          ls -la "${HOME}"
      - name: uname
        run: |
          echo "uname -a: $(uname -a)"
          echo "uname -s: $(uname -s)"
          echo "uname -n: $(uname -n)"
          echo "uname -r: $(uname -r)"
          echo "uname -v: $(uname -v)"
          echo "uname -m: $(uname -m)"
          echo "uname -p: $(uname -p)"
          echo "uname -o: $(uname -o)"
      - name: Set output
        id: hoge
        run: echo "hoge=fuga" | tee -a "${GITHUB_OUTPUT}"
      - name: Echo
        id: echo
        if: |
          (github.event_name == 'pull_request') &&
          (steps.hoge.outputs.hoge == 'fuga')
        run: echo "${{ steps.hoge.outcome }}"
      - name: outcome
        if: steps.echo.outcome == 'success'
        run: echo "${{ steps.echo.outcome }}"
      - name: outcome
        id: skipped
        if: false
        run: echo "skipped"
      - name: outcome skipped
        if: steps.skipped.outcome == 'success'
        run: echo "${{ steps.skipped.outcome }}"

  dump:
    name: dump-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Dump step1
        # if: false
        env:
          ID1: "dump-${{ matrix.os }}"
          ID2: "${{ format('{0}-{1}', 'dump', matrix.os) }}"
        run: |
          echo "dump-${{ matrix.os }}"
          echo "${ID1}"
          echo "${{ format('{0}-{1}', 'dump', matrix.os) }}"
          echo "${ID2}"
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
          # env | sort
          # jq < "${GITHUB_EVENT_PATH}"
      - name: Dump step2
        if: false
        id: step2
        run: |
          jq < "${GITHUB_EVENT_PATH}"
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
      - name: Dump without step id
        if: false
        run: |
          jq < "${GITHUB_EVENT_PATH}"
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
