name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: test
        run: |
          echo "${{ github.event_name == 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name != 'pull_request' && 'docker' || 'registry' }}"
          echo "${{ github.event_name == 'pull_request' && 'docker' }}"
          echo "${{ github.event_name == 'pull_request' || 'registry' }}"
          echo "${HOME}"
          ls -la "${HOME}"

  dump:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Dump step1
        id: step1
        run: |
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
          jq < "${GITHUB_EVENT_PATH}"
      - name: Dump step2
        id: step2
        run: |
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
          jq < "${GITHUB_EVENT_PATH}"
      - name: Dump without step id
        run: |
          env | sort
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(vars) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(inputs) }}"
          jq < "${GITHUB_EVENT_PATH}"
