name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Dump github context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
