name: GitHub API

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: step1
        id: step1
        run: sleep 1
      - name: step2
        id: step2
        run: sleep 2
      - name: step3
        id: step3
        run: sleep 3
  job2:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: step1
        id: step1
        run: sleep 1
      - name: step2
        id: step2
        run: sleep 2
      - name: step3
        id: step3
        run: sleep 3
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/github-script@v7
        id: dump
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100
            })
            console.log(JSON.stringify(result, null, 2));
