name: Vulnerability Scan

on:
  push:
    branches:
      - master    
#   schedule:
#     - cron: '0 9 * * *'

jobs:
  scan:
    runs-on: ubuntu-18.04
    steps:

      - run: docker pull "alpine:3.10.1"

      - uses: peaceiris/gitrivy@commit-hash
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: "alpine:3.10.1"
