name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@b785a39e04f3fa0d1f15523947c9cc9605be634d
        env:
          RUNNER_DEBUG: 1
#         with:
#           github_token: ${{ secrets.GH_PAT }}
#           config_file: .github/label-commenter-config.yml
