name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@b5bad42
        env:
          RUNNER_DEBUG: 1
        # with:
          # config_file: .github/label-commenter-config.yml
