name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@5e6a709cc6bdde2403490c452278f11731557396
        env:
          RUNNER_DEBUG: 1
        # with:
          # config_file: .github/label-commenter-config.yml
