name: Label Commenter

on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@e85c0a4f058824bb8496cc630a9efbba8b3e540d
        env:
          RUNNER_DEBUG: 1
#         with:
#           github_token: ${{ secrets.GH_PAT }}
#           config_file: .github/label-commenter-config.yml
