name: CI

on:
  push:
    branches:
      - "main"
  issue_comment:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # https://github.com/actions/checkout/releases/tag/v3.6.0
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GH_CXT: ${{ toJson(github) }}
        run: echo "${GH_CXT}"
      - run: gh pr checkout "${{ github.event.issue.number }}"
