name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        default: development
        required: true
        type: choice
        options:
          - development
          - production
  push:
    branches:
      - "main"

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Setup environments"
        run: |
          TMP_FILE=$(mktemp)"
          if [ "${{ github.event_name == 'push' || inputs.environment == 'development' }}" = "true" ]; then
            {
              echo "environment=development"
            } | tee -a "${TMP_FILE}"
          fi
          if [ "${{ inputs.environment == 'production' }}" = "true" ]; then
            {
              echo "environment=production"
            } | tee -a "${TMP_FILE}"
          fi
          cat "${TMP_FILE}" >> "${GITHUB_ENV}"

  release:
    needs: prepare
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0
      - run: echo ${{ env.environment }}
