name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        default: development
        required: true
        type: choice
        options:
          - development
          - production
  push:
    branches:
      - "main"
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - run: |
          cat << OBJECT
          echo ${{ toJson(github) }}
          OBJECT
      - run: git --no-pager log

      - name: Fetch base branch
        run: |
          echo ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.event.pull_request.base.sha }}
