name: CI

on:
  push:
    branches:
      - "main"
  issue_comment:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Dump GitHub context
        env:
          GH_CXT: ${{ toJson(github) }}
        run: echo "${GH_CXT}"
