name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # https://github.com/actions/checkout/releases/tag/v3.6.0
      - name: Dump GitHub context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
      - run: sleep 30

  coverage:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    concurrency:
      group: ${{ github.event_name == 'push' }} && ${{ github.workflow }}-${{ github.ref }}-${{ github.run_number }} || ${{ github.workflow }}-${{ github.ref }}-coverage
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # https://github.com/actions/checkout/releases/tag/v3.6.0
      - name: Dump GitHub context
        env:
          GH_CTX: ${{ toJson(github) }}
        run: echo "${GH_CTX}"
      - run: sleep 32
