name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      semver_type:
        description: "Semver type"
        required: true
        type: "choice"
        options:
          - "patch"
          - "minor"
          - "major"
        default: "patch"
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    env:
      HOGE: hoge
    steps:
      - name: set FUGA
        run: |
          echo 'FUGA=fuga' | tee -a "${GITHUB_ENV}"
      - name: echo test
        run: |
          echo $HOGE
          echo $PIYO
        env:
          PIYO: ${{ env.FUGA }}
