name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: |
          cat << EOF
          ${{ github.event_name }}
          ${{ github.event_name == 'schedule' }}
          EOF
