name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2

      - run: pwd
      - run: env

      - name: Set envs
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "GH_WORKFLOW=${GITHUB_WORKFLOW}" >> ${GITHUB_ENV}
          echo "GH_JOB=${GITHUB_JOB}" >> ${GITHUB_ENV}
          echo "GH_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: Run a one-line script
        run: echo "${{ env.GH_WORKFLOW }}/${{ env.GH_JOB }}/${{ env.GH_RUN_NUMBER }}"
