name: CI

on:
  push:
    branches:
      - "main"

jobs:
  prepare:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Dump
        run: |
          docker images
