name: Main CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  greeting:
    strategy:
      matrix:
        os:
          - 'ubuntu-18.04'
          #- 'macos-latest'
          #- 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2  # master
        # with:
          # ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
      #- uses: 'docker://docker.pkg.github.com/peaceiris/actions-gh-pages/action:latest'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          echo "hoge" >> README.md
          git commit -am "add hoge"
          git push origin master
      - run: gpg --version
      - run: env
      - run: |
          apt update
          apt install -y nkf
          nkf --version
      # - run: sh -c 'eval "$(ssh-agent)"'
      # - run: Start-Process powershell.exe -Verb runas
      - run: git --version
      - run: ssh -V
      - run: openssl version

  push-latest:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    env:
      DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/playground
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "::set-env name=PKG_TAG::${DOCKER_BASE_NAME}:latest"

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag "${PKG_TAG}"

      - name: Test
        run: |
          docker run --rm "${PKG_TAG}"

      - name: Login to Package Registry
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u peaceiris --password-stdin

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker push "${PKG_TAG}"

#    - name: Hello from GitHub Package Registry
#      uses: docker://docker.pkg.github.com/peaceiris/playground-actions/latest:latest
