name: Main CI

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize]

jobs:
  greeting:
    runs-on: ubuntu-18.04
    #runs-on: macos-latest
    #runs-on: windows-latest
    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${GITHUB_CONTEXT}"

    - name: hello
      run: |
        pwd
        #ls -la
        #which shasum

    - run: echo ${HOME}
    - run: echo ${GITHUB_WORKSPACE}
    #- run: which certutil

#    - name: Hello from GitHub Package Registry
#      uses: docker://docker.pkg.github.com/peaceiris/playground-actions/latest:latest

  push-latest:
    runs-on: ubuntu-18.04
    env:
      DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/playground
    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set env
      run: |
        echo "::set-env name=PKG_LATEST::${DOCKER_BASE_NAME}:latest"

    - name: Build image
      run: |
        docker build . --file Dockerfile --tag "${PKG_LATEST}"

    - name: Test
      run: |
        docker run --rm "${PKG_LATEST}"

    - name: Login to Package Registry
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u peaceiris --password-stdin

    - name: Push latest
      if: github.ref == 'refs/heads/master'
      run: |
        docker push "${PKG_LATEST}"
