name: Main CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  greeting:
    strategy:
      matrix:
        os:
          - 'ubuntu-18.04'
          #- 'macos-latest'
          #- 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

  push-latest:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    env:
      DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/playground
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "PKG_TAG=${DOCKER_BASE_NAME}:latest" >> ${GITHUB_ENV}

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag "${PKG_TAG}"

      - name: Test
        run: |
          docker run --rm "${PKG_TAG}"

      - name: Login to Package Registry
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u peaceiris --password-stdin

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker push "${PKG_TAG}"

#    - name: Hello from GitHub Package Registry
#      uses: docker://docker.pkg.github.com/peaceiris/playground-actions/latest:latest
