name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Set env
        run: echo "::set-env name=TAG_NAME::${GITHUB_REF##refs/tags/}"

      - name: Validate tag format
        run: npx semver "${TAG_NAME}"

      - name: Is prerelease
        id: is-prerelease
        run: |
          if [ -n "$(echo "${TAG_NAME}" | grep '\-')" ]; then
            # export IS_PRERELEASE="true"
            export IS_PRERELEASE="-prerelease"
          else
            # export IS_PRERELEASE="false"
            export IS_PRERELEASE=""
          fi
          # echo "::set-output name=IS_PRERELEASE::${IS_PRERELEASE}"
          echo "::set-env name=IS_PRERELEASE::${IS_PRERELEASE}"

      - name: Setup ghr
        run: |
          export GHR_VERSION="v0.13.0"
          export GHR_NAME="ghr_${GHR_VERSION}_linux_amd64"
          export GHR_TARBALL="${GHR_NAME}.tar.gz"
          wget "https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/${GHR_TARBALL}"
          tar -zxvf "${GHR_TARBALL}"
          mkdir ~/bin
          mv "./${GHR_NAME}/ghr" ~/bin/
          echo "::add-path::~/bin"
          rm -rf "./${GHR_NAME}" "./${GHR_TARBALL}"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # https://github.com/tcnksm/ghr
          ghr \
            -t "${GITHUB_TOKEN}" \
            # -u USERNAME \
            -r "${GITHUB_REPOSITORY}" \
            -c "${GITHUB_SHA}" \
            -n "Release ${TAG_NAME}" \
            -b "./CHANGELOG.md" \
            # -p NUM \
            # -replace \  # Replace artifacts if it is already uploaded
            -draft \
            -soft \
            "${IS_PRERELEASE}" \
            "${TAG_NAME}" assets/

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           draft: true
#           prerelease: ${{ steps.is-prerelease.outputs.IS_PRERELEASE }}
#           body_path: CHANGELOG.md
#           files: |
#             asset_1.txt
#             asset_2.txt
