name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1

      - name: Is prerelease
        id: is-prerelease
        run: |
          export TAG_NAME="${GITHUB_REF##refs/tags/}"
          if [ -n "$(echo "${TAG_NAME}" | grep '\-')" ]; then
            export IS_PRERELEASE="true"
          else
            export IS_PRERELEASE="false"
          fi
          echo "::set-output name=IS_PRERELEASE::${IS_PRERELEASE}"

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ steps.is-prerelease.outputs.IS_PRERELEASE }}
          # body_path: path/to/body_path.txt
          # files: path/to/assets.txt
