name: workflow totalization

# https://qiita.com/yusuke-sasaki/items/60cc128233a1b602c9e8

on:
  push:

jobs:
  summary:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    # permissions:
    #   contents: read
    #   actions: read
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: step1
        id: step1
        run: sleep 1
      - name: step2
        id: step2
        run: sleep 2
      - name: step3
        id: step3
        run: sleep 3
      - uses: actions/github-script@v7
        id: dump
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
            console.log(JSON.stringify(github, null, 2));

            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100
            })

            console.log(JSON.stringify(result, null, 2));
