name: workflow totalization

# https://qiita.com/yusuke-sasaki/items/60cc128233a1b602c9e8

on:
  push:

jobs:
  summary:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100,
              0
            })

            console.log(JSON.stringify(result, null, 2));
